name = input("What is your name? ")
age = int(input("How old are you? "))
city = input("Where do you live? ")
print("Hello, {name}" .format(name = name))
print(f"Your age is {age}")
print("You live in %s" % city )
